# Security stage jobs

dependency-scan:
  stage: security
  rules:
    - if: "$CI_PIPELINE_SOURCE == 'merge_request_event' || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
  script:
    - sbt -v dependencyUpdates || true
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - target/dependency-check-report.*
